### list developers
GET http://localhost:3000/developers

### get developer
GET http://localhost:3000/developers/dev_IGXrlL-APqda-nk8MXUEj

### create developer
POST http://localhost:3000/developers
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@mail.com",
    "dateOfBirth": "1990-01-01"
}

### update developer
PATCH http://localhost:3000/developers/dev_IGXrlL-APqda-nk8MXUEj
Content-Type: application/json

{
    "email": "johnedited@mail.com"
}

### delete developer
DELETE http://localhost:3000/developers/3

